{
  width : 48, height : 48, bpp : 4,
  transparent : 0,
  buffer : require("heatshrink").decompress(atob("AH4Aph////wCqgEBDKIWBA4oYOh4ODAhIAIFowKOEgIjLGBQ7MEhIuMEpQIBGBQkBEw6CNB5JGOJBD9QFAwXEDhYXFJwpMLCJgwLC5aVLIJn/C5wPH/4wJCQgOHh4wJIQnwJBAhHCIoXIPJAXGdx5HGQ5R3MdJa/TC9B4QCIwXRGpQXSMCAoGMB73JJRY9BH5BIOEhJIMEpQwMEhf/BSiCGAhIYKEw3/ch4YBDIQDBfaAZECqQA/AC4="))
}
